"""How many stages and viewers does one process actually carry?

The scaling claim in the README should be a measurement, not an assertion, and
this is the measurement. It starts a server with N stages, attaches M viewer
WebSockets, and reports what the process costs while captions are flowing.

Two things it deliberately does and does not measure.

It runs the `fake` transcription backend, so it costs nothing and needs no
credentials -- and it measures **the process**: decoding audio, moving captions
through the bus, and serving sockets. It does not measure the model's own
concurrency, which is a quota question and is answered by your API tier rather
than by this machine.

Delivery latency is measured end to end: the time between a caption being
published and a real WebSocket client receiving it, across every connected
viewer.

    python scripts/loadtest.py --stages 20 --viewers 100
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import statistics
import subprocess
import sys
import time
from pathlib import Path

import psutil
import websockets

ROOT = Path(__file__).resolve().parents[1]
PORT = 8123


def write_config(stages: int, path: Path) -> None:
    samples = ["./samples/keynote-en.wav", "./samples/charla-es.wav"]
    langs = [("en", ["es", "pt"]), ("es", ["en"])]
    lines = [
        "# Generated by scripts/loadtest.py. Not meant to be edited.",
        "stt:",
        "  backend: fake",
        "translation:",
        "  enabled: false",
        "features:",
        "  catchup_buffer: 50",
        "sessions:",
    ]
    for i in range(stages):
        src, (lang, targets) = samples[i % 2], langs[i % 2]
        lines += [
            f"  - id: stage-{i:02d}",
            f'    title: "Stage {i:02d}"',
            f"    source: {{ type: file, path: {src}, loop: true }}",
            f"    source_language: {lang}",
            f"    targets: [{', '.join(targets)}]",
        ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


async def viewer(url: str, latencies: list[float], stop: asyncio.Event) -> int:
    """One audience member. Returns how many captions they received."""
    received = 0
    try:
        async with websockets.connect(url, open_timeout=20, ping_interval=20) as ws:
            while not stop.is_set():
                try:
                    raw = await asyncio.wait_for(ws.recv(), timeout=1.0)
                except asyncio.TimeoutError:
                    continue
                msg = json.loads(raw)
                received += 1
                sent = msg.get("emitted_at")
                if sent:
                    # Both clocks are this machine's, so the difference is the
                    # time from publishing to arrival at a real client.
                    latencies.append((time.time() - sent) * 1000)
    except Exception:
        pass
    return received


async def run(stages: int, viewers: int, seconds: int) -> int:
    cfg = ROOT / ".loadtest.yaml"
    write_config(stages, cfg)

    env = {**os.environ, "PYTHONUNBUFFERED": "1", "PYTHONIOENCODING": "utf-8"}
    proc = subprocess.Popen(
        [sys.executable, "-m", "calandria", "-c", str(cfg), "--port", str(PORT)],
        cwd=ROOT, env=env, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    server = psutil.Process(proc.pid)

    try:
        base = f"http://127.0.0.1:{PORT}"
        for _ in range(60):
            await asyncio.sleep(1)
            try:
                import urllib.request
                urllib.request.urlopen(f"{base}/healthz", timeout=2).read()
                break
            except Exception:
                if proc.poll() is not None:
                    print("the server exited during startup", file=sys.stderr)
                    return 1
        else:
            print("the server never became healthy", file=sys.stderr)
            return 1

        print(f"{stages} stages, {viewers} viewers, {seconds}s\n")
        await asyncio.sleep(6)          # let every stage open its source

        latencies: list[float] = []
        stop = asyncio.Event()
        proto = "ws"
        tasks = [
            asyncio.create_task(viewer(
                f"{proto}://127.0.0.1:{PORT}/ws/captions"
                f"?session=stage-{i % stages:02d}&lang="
                f"{'en' if (i % stages) % 2 == 0 else 'es'}&replay=0",
                latencies, stop))
            for i in range(viewers)
        ]
        await asyncio.sleep(3)          # let them all connect

        # Measure the whole tree. `python -m` leaves a thin launcher in front
        # of the real server, so the parent alone reports a few megabytes of
        # nothing -- and ffmpeg is a genuine part of what a stage costs, not an
        # externality to be left out of the total.
        #
        # The Process objects are cached by pid rather than rebuilt each round:
        # cpu_percent() measures the interval since the previous call *on the
        # same object*, so a freshly constructed one always answers 0.0. That
        # reads as a result rather than as the missing baseline it is.
        known: dict[int, psutil.Process] = {}

        def tree() -> list[psutil.Process]:
            live = [server]
            try:
                live += server.children(recursive=True)
            except psutil.Error:
                pass
            out = []
            for proc_ in live:
                cached = known.get(proc_.pid)
                if cached is None:
                    cached = proc_
                    known[proc_.pid] = cached
                    try:
                        cached.cpu_percent(None)   # establish the baseline
                    except psutil.Error:
                        continue
                out.append(cached)
            return out

        tree()                                     # prime everything running now
        await asyncio.sleep(1)

        samples_cpu, samples_rss, samples_ff = [], [], []
        started = time.monotonic()
        while time.monotonic() - started < seconds:
            await asyncio.sleep(2)
            cpu = rss = 0.0
            ffmpegs = 0
            for proc_ in tree():
                try:
                    with proc_.oneshot():
                        cpu += proc_.cpu_percent(None)
                        rss += proc_.memory_info().rss / 1e6
                        if "ffmpeg" in proc_.name().lower():
                            ffmpegs += 1
                except psutil.Error:
                    continue                       # a looping source recycled
            samples_cpu.append(cpu)
            samples_rss.append(rss)
            samples_ff.append(ffmpegs)
            print(f"  [{time.monotonic()-started:4.0f}s] "
                  f"cpu {cpu:5.1f}%  rss {rss:6.1f} MB  "
                  f"ffmpeg {ffmpegs:>3}  captions {len(latencies):>6}", flush=True)

        stop.set()
        counts = await asyncio.gather(*tasks)

        cores = os.cpu_count() or 1
        cpu = statistics.median(samples_cpu) if samples_cpu else 0.0
        lat = sorted(latencies)
        print("\n=== one process ===")
        print(f"  stages                : {stages}")
        print(f"  viewer sockets        : {viewers} ({sum(counts)} captions delivered)")
        print(f"  cpu, median           : {cpu:.1f}% of one core "
              f"({cpu/cores:.1f}% of this {cores}-core machine)")
        print(f"  cpu per stage         : {cpu/stages:.2f}% of one core")
        print(f"  memory, whole tree    : {statistics.median(samples_rss):.0f} MB")
        print(f"  ffmpeg processes      : {statistics.median(samples_ff):.0f}")
        if lat:
            print(f"  publish -> viewer     : p50 {lat[len(lat)//2]:.1f} ms · "
                  f"p95 {lat[int(len(lat)*0.95)]:.1f} ms")
        rss_med = statistics.median(samples_rss)
        if cpu > 0:
            per_cpu, per_mem = cpu / stages, rss_med / stages
            by_cpu, by_mem = int(100 / per_cpu), int(8000 / per_mem)
            print()
            print(f"  per stage             : {per_cpu:.2f}% of a core · {per_mem:.0f} MB")
            print(f"  one core saturates at : ~{by_cpu} stages")
            print(f"  8 GB holds            : ~{by_mem} stages")
            print(f"  binds first here      : {'memory' if by_mem < by_cpu else 'CPU'}")
            print("  In practice your API quota binds well before either.")
        print("\n  Measured: decoding, fan-out and sockets. The model's own")
        print("  concurrency is a quota question, answered by your API tier.")
        return 0
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.kill()
        cfg.unlink(missing_ok=True)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--stages", type=int, default=20)
    ap.add_argument("--viewers", type=int, default=100)
    ap.add_argument("--seconds", type=int, default=40)
    a = ap.parse_args()
    return asyncio.run(run(a.stages, a.viewers, a.seconds))


if __name__ == "__main__":
    raise SystemExit(main())
